config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user_registrations" }
  # devise_for :users
  resources :products do
    resources :comments
 end
    resources :users

  post 'payments/create'

  get 'static_pages/thanks_payment' => 'thank_you'

  get 'payments/thanks'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

root 'static_pages#landing_page'

mount ActionCable.server => '/cable'

resources :orders, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

    validates :name, presence: true


def average_rating
  comments.average(:rating).to_f
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @products = Product.where("name ilike ?", "%#{search_term}%")
      else
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      end
    else
      @products = Product.all
    end
  end
  
  

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").page(params[:page]).per_page(5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    if params[:q1]
      id_product = params[:q1]
      @product = Product.find(id_product)
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
     if params[:q1]
        id_product = params[:q1]
        @product = Product.find(id_product)
      else
        @product = Product.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
      <hr>
      <p><%= comment.body %></p>
        <p>
        	<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        	<% if signed_in? && current_user.admin? %>
        		<%= link_to 'Destroy', product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        	<% end %>
        </p>
        <p><%= "Rating: #{comment.rating}/5" %></p>
        <div class="rated" data-score="<%= comment.rating %>"></div>
        <br>
  <% end %>
</div>s

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build]) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <div class="rating">
      <%= f.label :rating %><br>
      <%= f.text_field :rating, class: "rating" %>
      </div>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <%end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4 each_product">
<% cache product do %>
  <div class="thumbnail">
    <%= image_tag("spot.jpg", class: "img-responsive") %>
  </div>
 
    <h1 class="item_name"><%= product.name %></h1>
    <ul>
     <li>Description: <%= product.description %></p></li> 
      <li>Color: <%= product.color %></li>
      <li><strong> $ <%= product.price %></strong></li>
    </ul>
    <div class="buttons">
      <%= link_to 'Show', product, class:"btn btn-primary", role:"button"%>
      <%= link_to 'Edit', edit_product_path(product), class:"btn btn-default", role:"button" %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-danger", role:"button" %>
      <% end %>
      
    </div>
   </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
 <% cache(cache_key_for_products) do %>
  <%= render @products %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
  <div class="container-fluid">
    <div class="row" data-product-id="<%= @product.id %>">
      <div class="col-md-6 col-xs-12">
      <% cache @product do %>
          <h1 class="title"><%= @product.name %></h1>
      
  
        <div>
         <%= image_tag("spot.jpg", width: "350", class: "img-zoom") %>
        </div>
 
 
      <div class="col-md-6 col-xs-12">
        
        <h3>Description</h3>
        <p class="description"><%= @product.description %></p>
  
        <h3>Price</h3>
        <p class="price"><%= @product.price %></p>

        <h3>Color</h3>
        <p class="color"><%= @product.color %></p>
          <% end %>
        <p>Average Rating:
        
        <div class="rated" data-score="<%= @product.average_rating %>" id="average_rating"></div>
       </p>
      </div>

        <%= form_tag "/payments/create" do %>
          <script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:pk_test_jorlSdkOLXxfzlYUu6ITiNil] %>"
  data-amount="<%= (@product.price).to_i %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  #data-image="<%= @product.image_url %>">
  </script>
    <%= hidden_field_tag(:product_id, @product.id) %>
  <% end %>
     
      

        <%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to "Delete Product", product_path(@product), method: :delete, data: { confirm: "Are you sure?" } %>
       
      
      

<div class="col-md-6 col-md-offset-3">
<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
  <%= render 'comments' %>
</div>
<div class="col-md-6 col-md-offset-3">
<%= render 'new_comment' %>
<div class="col-md-6 col-md-offset-3">
 <%= will_paginate @comments %>




      
    </div>
  </div>
  