config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user_registrations" }
  # devise_for :users
  resources :products do
    resources :comments
 end
    resources :users

  post 'payments/create'

  get 'static_pages/thanks_payment' => 'thank_you'

  get 'payments/thanks'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

root 'static_pages#landing_page'

mount ActionCable.server => '/cable'

resources :orders, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bike Berlin</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= action_cable_meta_tag %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href="/static_pages/landing_page.html">Berlin Bikes</a>
      
    </div>
    
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
          <%= link_to '/static_pages/index' do %>
          <%= content_tag :span, "(current)", :class => "sr-only" %>
          Home
          <% end %>
          </li>
          <li><a href="<%= products_path %>">Products</a></li>
          <li><a href="<%= static_pages_about_path %>">About</a></li>
          <li><a href="<%= static_pages_contact_path %>">Contact</a></li>
         <%= form_tag("/products", class:"navbar-form navbar-left", role:"search", method:"get") do %>
         <%= content_tag(:div, text_field_tag('q', nil, class:"form-control", placeholder:"search"), class:"form-group") %>
        <%= submit_tag("Search", class:"btn btn-default") %>  
        </ul>
        <ul class="nav pull-right">
          <li>
           <% if user_signed_in? %>
            <%=link_to('Logout', destroy_user_session_path, :method => :delete) %>
           <% else %>
             <%=link_to('Login', new_user_session_path) %>
          <% end %>
          </li>
        </ul>
           
<% end %>
     </div>
    </div>
    </nav> <!-- end navbar -->
    <% if notice %>
  <div class="alert alert-warning" role="alert" id="alert">
    <p class="notice"><%= notice %></p>
    </div>
    <% end %>
    <% if alert %>
  <div class="alert alert-warning" role="alert" id="alert">
    <p class="alert"><%= alert%></p>
   </div>
  <% end %>  
<%= yield %>
<footer class="navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <span>&copy; 2016 Bike Berlin</span>
  </div>
</footer>
</body>
</html>